# Generated by Django 3.1.4 on 2020-12-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnrouteFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(max_length=255)),
                ('aircraft', models.CharField(max_length=255)),
                ('tas_filed', models.IntegerField(blank=True, null=True)),
                ('tas_actual', models.IntegerField(blank=True, null=True)),
                ('prev_fix', models.CharField(blank=True, max_length=255, null=True)),
                ('prev_fix_time', models.IntegerField(blank=True, null=True)),
                ('prev_fix_time_rev', models.IntegerField(blank=True, null=True)),
                ('prev_fix_time_actual', models.IntegerField(blank=True, null=True)),
                ('post_fix_plus', models.IntegerField(blank=True, null=True)),
                ('post_fix_time', models.IntegerField(blank=True, null=True)),
                ('post_fix_time_actual', models.IntegerField(blank=True, null=True)),
                ('post_fix', models.CharField(blank=True, max_length=255, null=True)),
                ('altitude', models.IntegerField(blank=True, null=True)),
                ('next_fix', models.CharField(blank=True, max_length=255, null=True)),
                ('next_fix_time', models.IntegerField(blank=True, null=True)),
                ('arrival', models.BooleanField()),
                ('requested_altitude', models.IntegerField(blank=True, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('transponder', models.IntegerField(blank=True, null=True)),
                ('coast', models.BooleanField(default=False)),
                ('discarded', models.BooleanField(default=False)),
            ],
        ),
    ]
